// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'orders_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OrdersResponse _$OrdersResponseFromJson(Map<String, dynamic> json) =>
    OrdersResponse(
      id: (json['id'] as num).toInt(),
      ids: json['ids'] as String?,
      type: json['type'] as String?,
      cateId: json['cate_id'] as String?,
      serviceId: json['service_id'] as String?,
      mainOrderId: (json['main_order_id'] as num?)?.toInt(),
      serviceType: json['service_type'] as String?,
      apiProviderId: (json['api_provider_id'] as num?)?.toInt(),
      apiServiceId: json['api_service_id'] as String?,
      apiOrderId: (json['api_order_id'] as num?)?.toInt(),
      uid: json['uid'] as String?,
      link: json['link'] as String?,
      quantity: json['quantity'] as String?,
      usernames: json['usernames'] as String?,
      username: json['username'],
      hashtags: json['hashtags'],
      hashtag: json['hashtag'] as String?,
      media: json['media'] as String?,
      comments: json['comments'] as String?,
      subPosts: (json['sub_posts'] as num?)?.toInt(),
      subMin: (json['sub_min'] as num?)?.toInt(),
      subMax: (json['sub_max'] as num?)?.toInt(),
      subDelay: (json['sub_delay'] as num?)?.toInt(),
      subExpiry: json['sub_expiry'] as String?,
      subResponseOrders: json['sub_response_orders'],
      subResponsePosts: json['sub_response_posts'],
      subStatus: json['sub_status'],
      charge: json['charge'] as String?,
      formalCharge: json['formal_charge'],
      profit: json['profit'],
      status: json['status'] as String?,
      startCounter: json['start_counter'],
      remains: json['remains'] as String?,
      isDripFeed: (json['is_drip_feed'] as num?)?.toInt(),
      runs: (json['runs'] as num?)?.toInt(),
      interval: (json['interval'] as num?)?.toInt(),
      dripfeedQuantity: json['dripfeed_quantity'] as String?,
      refill: (json['refill'] as num?)?.toInt(),
      refillStatus: json['refill_status'],
      refillDate: json['refill_date'],
      note: json['note'] as String?,
      changed: json['changed'],
      created: json['created'],
    );

Map<String, dynamic> _$OrdersResponseToJson(OrdersResponse instance) =>
    <String, dynamic>{
      'id': instance.id,
      'ids': instance.ids,
      'type': instance.type,
      'cate_id': instance.cateId,
      'service_id': instance.serviceId,
      'main_order_id': instance.mainOrderId,
      'service_type': instance.serviceType,
      'api_provider_id': instance.apiProviderId,
      'api_service_id': instance.apiServiceId,
      'api_order_id': instance.apiOrderId,
      'uid': instance.uid,
      'link': instance.link,
      'quantity': instance.quantity,
      'usernames': instance.usernames,
      'username': instance.username,
      'hashtags': instance.hashtags,
      'hashtag': instance.hashtag,
      'media': instance.media,
      'comments': instance.comments,
      'sub_posts': instance.subPosts,
      'sub_min': instance.subMin,
      'sub_max': instance.subMax,
      'sub_delay': instance.subDelay,
      'sub_expiry': instance.subExpiry,
      'sub_response_orders': instance.subResponseOrders,
      'sub_response_posts': instance.subResponsePosts,
      'sub_status': instance.subStatus,
      'charge': instance.charge,
      'formal_charge': instance.formalCharge,
      'profit': instance.profit,
      'status': instance.status,
      'start_counter': instance.startCounter,
      'remains': instance.remains,
      'is_drip_feed': instance.isDripFeed,
      'runs': instance.runs,
      'interval': instance.interval,
      'dripfeed_quantity': instance.dripfeedQuantity,
      'refill': instance.refill,
      'refill_status': instance.refillStatus,
      'refill_date': instance.refillDate,
      'note': instance.note,
      'changed': instance.changed,
      'created': instance.created,
    };
